data:
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPW5rMTI0MHN0b3JhZ2Vwcm9qZWN0MjtBY2NvdW50S2V5PVpJOWIrQloyVW9UZTVCZnNLTFVLenl1MUVOQjFJcVVpL1VlL3VWN3BNL2tQOVZJSG9IN1BqUTIzZmJFZjg5RE0yVWo2WWVTNkJUSlM4Qmx2WmtzUWVnPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  APPINSIGHTS_INSTRUMENTATIONKEY: OGE0YTFjNzktY2NlZC00MGJlLWE1M2EtOTk5MTJlMWMzZGIy
  APPLICATIONINSIGHTS_CONNECTION_STRING: SW5zdHJ1bWVudGF0aW9uS2V5PThhNGExYzc5LWNjZWQtNDBiZS1hNTNhLTk5OTEyZTFjM2RiMjtJbmdlc3Rpb25FbmRwb2ludD1odHRwczovL3dlc3R1cy0wLmluLmFwcGxpY2F0aW9uaW5zaWdodHMuYXp1cmUuY29tLw==
  FUNCTIONS_EXTENSION_VERSION: fjM=
  nk1240DBConnection: bW9uZ29kYjovL25rMTI0MGNvc21vc3Byb2plY3QyOjB1NnFkQzJaOEg5SFR2YU1PY3V5U1F1bmdzYUZuS2JhaGtuTEVWZ1ZTa3Flb3R5MEZNUG5naFlHbzFRbmdtSTBtTWVsMVJ4OFExQ0hBc0o3dXJnRUpRPT1AbmsxMjQwY29zbW9zcHJvamVjdDIubW9uZ28uY29zbW9zLmF6dXJlLmNvbToxMDI1NS8/c3NsPXRydWUmcmVwbGljYVNldD1nbG9iYWxkYiZyZXRyeXdyaXRlcz1mYWxzZSZtYXhJZGxlVGltZU1TPTEyMDAwMCZhcHBOYW1lPUBuazEyNDBjb3Ntb3Nwcm9qZWN0MkA=
apiVersion: v1
kind: Secret
metadata:
  name: nk1240aksproject2
---
data:
  host.master: cy9TRzRycThrQlFXTWgvL3pyekVrMFZxN25VclhFWWpOWHVxWk5iamQyRkhvZ3hTZ0Fnc0pRPT0=
  host.function.default: SEVSaW9aa2NIWkJ3c2pYV0hIbmxCckJuNi9jTE5Sci9XUzlVNThkNG5aZnZVb1FPb3M4R2JRPT0=
  host.systemKey.default: TUVQNkJGZ3RQTVJyVmZlYUI4Z0kyTXMxSllVQUhlVUVyUjJIUW11cmlhN3JRSDM4RC9iZFNnPT0=
  functions.createadvertisement.default: RTZVazFiZFlsWnZFdldGd3NBYVVzcURxOTdQZHNVdDJvSGJyRFkycUk5RVk0YUdqWm53OHFBPT0=
  functions.deleteadvertisement.default: dHRqaVVQbjV0QXJqenkvYXRlZ1VQYWNoejJ2dUFsY1NqWVJIalJEa3RTQ29VR3AvMC81YW9nPT0=
  functions.getadvertisement.default: Z2NocDMvakI0alpucTk1aWJKLzdEeGxKS3RocjBmc3I3SVViSGtRZ08zSURFZFZNdUxQajd3PT0=
  functions.getadvertisements.default: QVY3a2RXNlJxMWFCbkd4NVRHR2NmUWNJZTdhVTdUeHN4aVdnUXpOaE5YSWNpSi9ETjNhT3lRPT0=
  functions.getpost.default: YkI4R2Nwa2hZaVhGbVNGWmRVS1lFcndkMlEzUlAxa3ByQzFoZkg2TjBRVWFha2tTb1dBUmdRPT0=
  functions.getposts.default: VG5vRDJHdVp4UG5sc0ZUUzJXSjczWjUwWE01MlViVWNrVkVnNUUvQzdtbFJhZWlsQlBlUmZRPT0=
  functions.updateadvertisement.default: YmJCb1U1QU1SaFMxelJhS25DRXgyMG9QaHJ3ZURxMmpFMmhEcXZ0M0dhY25MVVRGVGV2YTdBPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-nk1240aksproject2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nk1240aksproject2-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: nk1240aksproject2-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nk1240aksproject2-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: nk1240aksproject2-http
spec:
  selector:
    app: nk1240aksproject2-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nk1240aksproject2-http
  labels:
    app: nk1240aksproject2-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nk1240aksproject2-http
  template:
    metadata:
      labels:
        app: nk1240aksproject2-http
    spec:
      containers:
      - name: nk1240aksproject2-http
        image: nk1240registryproject2.azurecr.io/nk1240project2
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-nk1240aksproject2
        envFrom:
        - secretRef:
            name: nk1240aksproject2
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: nk1240aksproject2-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nk1240aksproject2
  labels:
    app: nk1240aksproject2
spec:
  selector:
    matchLabels:
      app: nk1240aksproject2
  template:
    metadata:
      labels:
        app: nk1240aksproject2
    spec:
      containers:
      - name: nk1240aksproject2
        image: nk1240registryproject2.azurecr.io/nk1240project2
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: nk1240aksproject2
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: nk1240aksproject2-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nk1240aksproject2
  labels: {}
spec:
  scaleTargetRef:
    name: nk1240aksproject2
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
      eventHubName: testhub
      connection: Endpoint=sb://udacityneighborly.servicebus.windows.net/;SharedAccessKeyName=allpolicy;SharedAccessKey=LOxUOkN13xN038T1VoSsmaTt4s7vq/+VCzduS5/nH9A=;EntityPath=testhub
---

